### ISSUE TITLE
Refactor backend code issues

### ISSUE THREAD

**Issue by joka** [liqd/adhocracy3#2179]
- [x] remove needless resources from database (performance)  #1896 and other middle
- [x] search implementation (performance) #1686 #1905  #1924 hard
- [x] working with workflow/permission/roles (development, DomainSpecificLanguage) partly #2132  #2175 hard
- [x] resource sheet implementation (development)  #2147 hard
- [x] colander schema only for validation (development) #2172 middle
- [x] view_config decorator for rest api views (development) #2176 middle
- [ ] config methods to add resource/sheet types (development) easy
- [ ] improve caching hits (performance) easy (make current concept work right) / middle (other caching concept)
- [x] update pyramid to 1.6 easy
- [x] update substanced 1.0 (rm _is_service_ flag, fix migrations) easy
- [ ] update colander to 1.2 (fix schemas with missing binding,  maybe remove needless workarounds)  easy
- [ ] prefix '/API' for all rest api resources (deployment) middle
- [ ] remove frontend_server (backend can do it the same way) (development, deployment) middle
- [ ] workflow per object instead per resource type (maintenance, development) middle
- [ ] remove find_service/add_service from pools, not used (development) easy
- [ ] remove sheet interfaces (development, maintenance (less migrations)) hard
- [ ] script to remove not used images (maintenance) easy
- [ ] cleanup TODO comments (development) middle
- [ ] use content_name instead of IResource to create resourcess (prepare more decoupling frontend/backend and backend internal) middle
- [ ] use sheet name instead of ISheet interface to create sheets (prepare more decoupling frontend/backend and backend internal) hard
 
- [ ] pyvenv instead of virtualenv (embrace standard way) (docs) easy
- [ ] build docs without warnings, add check to keep it that way (docs) middle
- [ ] nice python api documentation (docs) middle
- [ ] fix type annotations for functions / use python 3.5 typing module (docs) middle
- [ ] document all scripts / add help text output to documentation (maintenance, docs) easy
- [ ] narrative docs for backend development (docs) middle

**Comment by joka** [comment]
initial refactor issue list for domain `backend`. Other possible domains: `deployment`, `frontend`, `api`, `docs`
